{
 "title": "AWS Observability Accelerator - AMP Dashboard",
 "description": "Dashboard for Amazon Managed Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WorkspaceID",
    "query": "dimension_values(default,AWS/Prometheus,RuleEvaluations,Workspace)"
   },
   { "name": "datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# Ingestion Usage Metrics\n\nMetrics relating to ingestion usage of the AMP service"
   }
  },
  {
   "title": "Active Series Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expression": "SELECT SUM(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'ActiveSeries' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Workspace Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "expression": "SELECT AVG(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'IngestionRate' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Billing",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": {
    "content": "# Billing\n\nContains information relating to the cost of AMP\n\n"
   }
  },
  {
   "title": "Sum of Estimated AMP Charges (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 7 },
   "targets": [
    {
     "expression": "SELECT SUM(EstimatedCharges) FROM SCHEMA(\"AWS/Billing\", Currency,ServiceName) WHERE ServiceName = 'AmazonPrometheus'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}